server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;
    charset utf-8;

    # Gzip
    gzip on;
    gzip_types text/css text/javascript application/javascript image/svg+xml;

    # Cache: assets estáticos un año
    location /assets/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # Cache: HTML sin caché
    location ~* \.html$ {
        add_header Cache-Control "no-cache";
    }

    # Rutas limpias
    location / {
        try_files $uri $uri/ $uri.html =404;
    }
}
